package core

import (
	"encoding/json"
	"fmt"
	"strings"
)

// ReportToJSON serializes a Report to pretty-printed JSON.
func ReportToJSON(r *Report) ([]byte, error) {
	return json.MarshalIndent(r, "", "  ")
}

// ReportToMarkdown formats a Report as a readable Markdown document.
func ReportToMarkdown(r *Report) string {
	var b strings.Builder

	b.WriteString("# SecTUI Security Report\n\n")
	b.WriteString(fmt.Sprintf("**Date:** %s\n", r.Timestamp.Format("2006-01-02 15:04:05")))
	b.WriteString(fmt.Sprintf("**Score:** %d/100\n", r.Score))
	b.WriteString(fmt.Sprintf("**Duration:** %s\n", r.Duration.Round(1e6)))
	b.WriteString(fmt.Sprintf("**Modules scanned:** %s\n\n", strings.Join(r.ModulesScanned, ", ")))

	// Platform info.
	b.WriteString("## System Info\n\n")
	osLabel := fmt.Sprintf("%s %s", r.Platform.Distro, r.Platform.Version)
	if r.Platform.OS == OSDarwin {
		osLabel = fmt.Sprintf("macOS %s", r.Platform.Version)
	}
	b.WriteString(fmt.Sprintf("- **OS:** %s\n", osLabel))
	b.WriteString(fmt.Sprintf("- **Arch:** %s\n", r.Platform.Arch))
	b.WriteString(fmt.Sprintf("- **Init:** %s\n", r.Platform.InitSystem))
	b.WriteString(fmt.Sprintf("- **Package Manager:** %s\n\n", r.Platform.PackageManager))

	// Findings summary.
	counts := map[Severity]int{}
	for _, f := range r.Findings {
		counts[f.Severity]++
	}

	b.WriteString("## Summary\n\n")
	b.WriteString(fmt.Sprintf("| Severity | Count |\n"))
	b.WriteString(fmt.Sprintf("|----------|-------|\n"))
	for _, sev := range []Severity{SeverityCritical, SeverityHigh, SeverityMedium, SeverityLow, SeverityInfo} {
		if c := counts[sev]; c > 0 {
			b.WriteString(fmt.Sprintf("| %s | %d |\n", strings.ToUpper(sev.String()), c))
		}
	}
	b.WriteString(fmt.Sprintf("\n**Total findings:** %d\n\n", len(r.Findings)))

	if len(r.Findings) == 0 {
		b.WriteString("No security findings. Your system looks good!\n")
		return b.String()
	}

	// Findings by module.
	b.WriteString("## Findings\n\n")

	moduleOrder := r.ModulesScanned
	grouped := map[string][]Finding{}
	for _, f := range r.Findings {
		grouped[f.Module] = append(grouped[f.Module], f)
	}

	for _, modID := range moduleOrder {
		findings, ok := grouped[modID]
		if !ok || len(findings) == 0 {
			continue
		}

		b.WriteString(fmt.Sprintf("### %s\n\n", modID))
		for _, f := range findings {
			title := T(f.TitleKey)
			if title == f.TitleKey {
				title = f.ID
			}
			sevLabel := strings.ToUpper(f.Severity.String())
			b.WriteString(fmt.Sprintf("- **[%s]** %s\n", sevLabel, title))
			if f.CurrentValue != "" {
				b.WriteString(fmt.Sprintf("  - Current: `%s`\n", f.CurrentValue))
			}
			if f.ExpectedValue != "" {
				b.WriteString(fmt.Sprintf("  - Expected: `%s`\n", f.ExpectedValue))
			}
			if f.FixID != "" {
				b.WriteString(fmt.Sprintf("  - Fix available: `%s`\n", f.FixID))
			}
		}
		b.WriteString("\n")
	}

	b.WriteString("---\n*Generated by SecTUI*\n")
	return b.String()
}
